// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMWZi0VCgNiKOjvnWI0fN3yPR6nOWQ0zA',
    appId: '1:315924639467:web:2c44ed16a0df97597f58ae',
    messagingSenderId: '315924639467',
    projectId: 'appkonserkita',
    authDomain: 'appkonserkita.firebaseapp.com',
    storageBucket: 'appkonserkita.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBZrAA7xhHRrXkQK5VlLJgbsO5tgbvdM',
    appId: '1:315924639467:android:2a77340d8b48e0057f58ae',
    messagingSenderId: '315924639467',
    projectId: 'appkonserkita',
    storageBucket: 'appkonserkita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiuyhAYuwX6VU8rxYkGpVprFVqImpQc-k',
    appId: '1:315924639467:ios:2881d40bd14f60a17f58ae',
    messagingSenderId: '315924639467',
    projectId: 'appkonserkita',
    storageBucket: 'appkonserkita.firebasestorage.app',
    iosBundleId: 'com.example.konserkitaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiuyhAYuwX6VU8rxYkGpVprFVqImpQc-k',
    appId: '1:315924639467:ios:2881d40bd14f60a17f58ae',
    messagingSenderId: '315924639467',
    projectId: 'appkonserkita',
    storageBucket: 'appkonserkita.firebasestorage.app',
    iosBundleId: 'com.example.konserkitaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMWZi0VCgNiKOjvnWI0fN3yPR6nOWQ0zA',
    appId: '1:315924639467:web:20be136d21732e5d7f58ae',
    messagingSenderId: '315924639467',
    projectId: 'appkonserkita',
    authDomain: 'appkonserkita.firebaseapp.com',
    storageBucket: 'appkonserkita.firebasestorage.app',
  );
}
